package packapi

import (
	"context"
	"fmt"
	"os"
	"strings"
	"sync"
	"testing"
	"time"
)

// These benchmarks compare the packing algorithms head-to-head on identical,
// deterministic instances, reporting BOTH speed (ns/op, the built-in metric) and
// solution quality as custom metrics: "bins" (containers used — lower is better)
// and "fill%" (packed volume ÷ used-bin volume — higher is tighter). Any items an
// algorithm can't place show up as "unfit".
//
// Run them with, e.g.:
//
//	go test ./packapi/ -bench BenchmarkAlgos3D -benchmem -run '^$'
//	go test ./packapi/ -bench BenchmarkAlgos      # all modes
//
// Running any BenchmarkAlgos* also writes a markdown comparison table to
// algo-bench.md (override the path with PACK_BENCH_MD=path). Plain `go test` and
// CI run no benchmarks, so they never touch the file.
//
// Because the instance is fixed per sub-benchmark, bins/fill% are constant across
// iterations; they're reported from the final solve.

// ─── markdown accumulation ──────────────────────────────────────────────────

type benchRow struct {
	mode, algo          string
	nsPerOp, bins, fill float64
	unfit               int
}

var (
	benchMu    sync.Mutex
	benchRows  = map[string]benchRow{} // keyed by "mode/algo"; last write wins
	benchOrder []string                // insertion order of keys
	benchMeta  = map[string]string{}   // mode → instance description
)

// recordBench stores one algorithm's result. Go may invoke a benchmark func
// several times while sizing b.N; keying by mode/algo and overwriting keeps just
// the final run per algorithm.
func recordBench(r benchRow) {
	benchMu.Lock()
	defer benchMu.Unlock()
	k := r.mode + "/" + r.algo
	if _, ok := benchRows[k]; !ok {
		benchOrder = append(benchOrder, k)
	}
	benchRows[k] = r
}

// TestMain runs the suite, then — if any algorithm benchmark recorded a result —
// writes the markdown comparison. It owns os.Exit for the package.
func TestMain(m *testing.M) {
	code := m.Run()
	if len(benchOrder) > 0 {
		if err := writeBenchMarkdown(); err != nil {
			fmt.Fprintln(os.Stderr, "bench markdown:", err)
		}
	}
	os.Exit(code)
}

func fmtDuration(ns float64) string {
	return time.Duration(int64(ns)).Round(time.Microsecond).String()
}

func writeBenchMarkdown() error {
	path := os.Getenv("PACK_BENCH_MD")
	if path == "" {
		path = "algo-bench.md"
	}

	// Group rows by mode, preserving the order modes first appeared.
	var modes []string
	byMode := map[string][]benchRow{}
	for _, k := range benchOrder {
		r := benchRows[k]
		if _, seen := byMode[r.mode]; !seen {
			modes = append(modes, r.mode)
		}
		byMode[r.mode] = append(byMode[r.mode], r)
	}

	var b strings.Builder
	b.WriteString("# Algorithm comparison\n\n")
	b.WriteString("Generated by `go test ./packapi/ -bench BenchmarkAlgos`. ")
	b.WriteString("`fill%` = packed volume ÷ (bins × bin volume); higher is tighter. ")
	b.WriteString("Time is per solve (best of the benchmark's iterations).\n")
	for _, mode := range modes {
		fmt.Fprintf(&b, "\n## %s — %s\n\n", strings.ToUpper(mode), benchMeta[mode])
		b.WriteString("| Algorithm | Bins | Fill % | Unfit | Time/op |\n")
		b.WriteString("|-----------|-----:|-------:|------:|--------:|\n")
		for _, r := range byMode[mode] {
			fmt.Fprintf(&b, "| %s | %d | %.1f | %d | %s |\n",
				r.algo, int(r.bins), r.fill, r.unfit, fmtDuration(r.nsPerOp))
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ─── instances ──────────────────────────────────────────────────────────────

// benchMix builds n deterministic mixed-size items for a mode via a small LCG, so
// the set is reproducible across runs (mirrors the webdemo's bigMix palette).
func benchMix(mode string, n int, seed uint32) []ItemSpec {
	s := seed
	if s == 0 {
		s = 1
	}
	next := func() float64 { s = s*1664525 + 1013904223; return float64(s>>8) / (1 << 24) }
	pick := func(a []float64) float64 { return a[int(next()*float64(len(a)))%len(a)] }

	out := make([]ItemSpec, n)
	for i := range out {
		switch mode {
		case "1d":
			w := pick([]float64{1, 2, 2, 3, 3, 4, 4, 5, 6, 7, 8})
			out[i] = ItemSpec{ID: itoa(i), Width: w}
		case "2d":
			sz := []float64{10, 12, 15, 18, 20, 25, 30, 35, 40, 50}
			out[i] = ItemSpec{ID: itoa(i), Width: pick(sz), Height: pick(sz), AllowRotate: true}
		default:
			sz := []float64{1, 2, 2, 3, 3, 4, 4, 5, 6}
			out[i] = ItemSpec{ID: itoa(i), Width: pick(sz), Depth: pick(sz), Height: pick(sz), AllowRotate: true}
		}
	}
	return out
}

// ─── runners ────────────────────────────────────────────────────────────────

// runAlgoBench times one algorithm over the instance, reports quality metrics to
// the benchmark output, and records a row for the markdown table.
func runAlgoBench(b *testing.B, mode, algo string, bin BinSpec, items []ItemSpec) {
	req := PackRequest{Mode: mode, Algorithm: algo, Bin: bin, Items: items}
	volByID := make(map[string]float64, len(items))
	for _, it := range items {
		volByID[it.ID] = binVolume(mode, BinSpec{Width: it.Width, Height: it.Height, Depth: it.Depth})
	}

	var resp PackResponse
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		resp = PackCtx(context.Background(), req)
	}
	b.StopTimer()

	fill := 0.0
	if denom := float64(resp.BinsUsed) * binVolume(mode, bin); denom > 0 {
		fill = 100 * placedVolume(resp, volByID) / denom
	}
	b.ReportMetric(float64(resp.BinsUsed), "bins")
	b.ReportMetric(fill, "fill%")
	if n := len(resp.Unplaced); n > 0 {
		b.ReportMetric(float64(n), "unfit")
	}
	recordBench(benchRow{
		mode: mode, algo: algo,
		nsPerOp: float64(b.Elapsed().Nanoseconds()) / float64(b.N),
		bins:    float64(resp.BinsUsed), fill: fill, unfit: len(resp.Unplaced),
	})
}

func benchAlgos(b *testing.B, mode, desc string, bin BinSpec, items []ItemSpec, algos []string) {
	benchMu.Lock()
	benchMeta[mode] = desc
	benchMu.Unlock()
	for _, algo := range algos {
		algo := algo
		b.Run(algo, func(b *testing.B) { runAlgoBench(b, mode, algo, bin, items) })
	}
}

func BenchmarkAlgos3D(b *testing.B) {
	items := benchMix("3d", 500, 33)
	benchAlgos(b, "3d", "500 mixed boxes (sides 1–6) into a 20×20×20 bin", BinSpec{Width: 20, Depth: 20, Height: 20}, items,
		[]string{"ff", "ffd", "bfd", "nfd", "blf", "ems", "heightmap", "laff", "auto"})
}

func BenchmarkAlgos2D(b *testing.B) {
	items := benchMix("2d", 400, 22)
	benchAlgos(b, "2d", "400 mixed rectangles (10–50) into a 300×300 bin", BinSpec{Width: 300, Height: 300}, items,
		[]string{"ff", "ffd", "bfd", "nfd", "skyline", "auto"})
}

func BenchmarkAlgos1D(b *testing.B) {
	items := benchMix("1d", 1000, 11)
	benchAlgos(b, "1d", "1000 mixed items (1–8) into capacity-10 bins", BinSpec{Width: 10}, items,
		[]string{"ff", "bf", "wf", "ffd", "bfd", "wfd", "mffd", "auto"})
}
