// Command render produces isometric PNG renders of how each packing algorithm
// solves a set of benchmark-style 3-D instances — a browserless, pure-Go stand-in
// for the WebGL demo, meant for embedding in docs/READMEs.
//
// For every scenario it solves the instance with each algorithm (via packapi),
// renders the resulting bins isometrically, and tiles the algorithms into one
// contact-sheet PNG per scenario. A Markdown block linking the images is printed
// to stdout (and written to <out>/README.md) for pasting into docs.
//
// It is a SEPARATE module (its own go.mod, replace → parent) so its image deps
// never reach the main module. Run it from this directory:
//
//	cd cmd/render && go run .                 # writes ../../docs/renders/*.png
//	go run . -out /tmp/r -items 80 -size 300  # custom output / counts / cell size
//
// The scenarios mirror packapi's benchmarks in spirit but use smaller item counts
// so the thumbnails stay legible; they are illustrative, not the timed instances.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"math"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/W-Floyd/go-pack-bins/packapi"
	"github.com/fogleman/gg"
	"github.com/golang/freetype/truetype"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/goregular"
)

// labelFont is the parsed scalable Go font used for cell labels; a TrueType face
// (rather than a fixed bitmap font) keeps text crisp and proportional at any DPI.
var labelFont = func() *truetype.Font {
	f, err := truetype.Parse(goregular.TTF)
	if err != nil {
		panic(err)
	}
	return f
}()

func face(points float64) font.Face {
	return truetype.NewFace(labelFont, &truetype.Options{Size: points})
}

// scenario is one instance to render: a slug (for the file name), a human title,
// the bin, the items, and the algorithms to render.
type scenario struct {
	slug, title string
	bin         packapi.BinSpec
	items       []packapi.ItemSpec
	algos       []string
}

func main() {
	out := flag.String("out", "../../docs/renders", "output directory for PNGs + README.md")
	mdPrefix := flag.String("mdprefix", "docs/renders", "path prefix used in the emitted Markdown image links")
	cell := flag.Int("size", 560, "cell size in pixels (per algorithm)")
	cols := flag.Int("cols", 3, "algorithms per row in the contact sheet")
	nMixed := flag.Int("items", 70, "item count for the mixed scenario")
	nCarton := flag.Int("cartons", 90, "item count for the carton scenario")
	algoFilter := flag.String("algos", "", "comma-separated subset of algorithms to render (default: all)")
	scnFilter := flag.String("scn", "", "render only scenarios whose slug contains this substring")
	input := flag.String("input", "", "render a saved webdemo scenario (.json) instead of the built-ins")
	flag.Parse()

	// "auto" is omitted: it just races the others and renders as whichever one wins.
	algos := []string{"ff", "ffd", "blf", "ems", "fit", "heightmap", "laff", "layer", "blocks", "assemble"}
	if *algoFilter != "" {
		algos = strings.Split(*algoFilter, ",")
	}
	var scenarios []scenario
	if *input != "" {
		sc, err := loadScenario(*input, algos)
		if err != nil {
			fmt.Fprintln(os.Stderr, "render: ", err)
			os.Exit(1)
		}
		scenarios = []scenario{sc}
	} else {
		scenarios = []scenario{
			{
				slug: "mixed", title: "Mixed boxes (sides 1–6) into 10×10×10",
				bin:   packapi.BinSpec{Width: 10, Height: 10, Depth: 10},
				items: mixItems(*nMixed, 33), algos: algos,
			},
			{
				slug: "cartons", title: "Carton SKUs (sizes divide the bin) into 12×12×12",
				bin:   packapi.BinSpec{Width: 12, Height: 12, Depth: 12},
				items: cartonItems(*nCarton, 5), algos: algos,
			},
		}
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "render: ", err)
		os.Exit(1)
	}

	var md strings.Builder
	md.WriteString("# Algorithm packing renders\n\n")
	md.WriteString("Isometric renders of each algorithm's packing, generated by `cmd/render` (no browser).\n")

	for _, sc := range scenarios {
		if *scnFilter != "" && !strings.Contains(sc.slug, *scnFilter) {
			continue
		}
		img := renderScenario(sc, *cell, *cols)
		file := filepath.Join(*out, sc.slug+".png")
		if err := savePNG(file, img); err != nil {
			fmt.Fprintln(os.Stderr, "render: ", err)
			os.Exit(1)
		}
		link := path.Join(*mdPrefix, sc.slug+".png")
		fmt.Printf("rendered %s (%d algos) -> %s\n", sc.slug, len(sc.algos), file)
		fmt.Fprintf(&md, "\n## %s\n\n![%s](%s)\n", sc.title, sc.title, link)
	}

	mdPath := filepath.Join(*out, "README.md")
	if err := os.WriteFile(mdPath, []byte(md.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "render: ", err)
		os.Exit(1)
	}
	fmt.Println("\nMarkdown written to", mdPath)
	fmt.Print("\n", md.String())
}

// renderScenario solves the instance with each algorithm and tiles the per-algo
// renders into one contact-sheet image.
func renderScenario(sc scenario, cell, cols int) image.Image {
	colorOf := buildPalette(sc.items)
	dim := [3]float64{sc.bin.Width, sc.bin.Depth, sc.bin.Height}
	binVol := sc.bin.Width * sc.bin.Depth * sc.bin.Height

	rows := (len(sc.algos) + cols - 1) / cols
	sheet := gg.NewContext(cols*cell, rows*cell)
	sheet.SetRGB(1, 1, 1)
	sheet.Clear()

	for i, algo := range sc.algos {
		resp := packapi.PackCtx(context.Background(), packapi.PackRequest{
			Mode: "3d", Algorithm: algo, Bin: sc.bin, Items: sc.items,
		})
		fill := 0.0
		if resp.BinsUsed > 0 {
			placed := 0.0
			for _, p := range resp.Placements {
				placed += p.W * p.H * p.D
			}
			fill = 100 * placed / (float64(resp.BinsUsed) * binVol)
		}
		label := fmt.Sprintf("%s — %d bins, %.0f%% fill", algoLabel(algo), resp.BinsUsed, fill)
		if n := len(resp.Unplaced); n > 0 {
			label += fmt.Sprintf(", %d unfit", n)
		}
		ox := float64((i % cols) * cell)
		oy := float64((i / cols) * cell)
		drawCell(sheet, ox, oy, float64(cell), resp, dim, colorOf, label)
	}
	return sheet.Image()
}

// drawCell renders one algorithm's full packing (its bins tiled in a row) into the
// cell at (ox,oy), with a header label.
func drawCell(dc *gg.Context, ox, oy, cell float64, resp packapi.PackResponse, dim [3]float64, colorOf func(string) color.RGBA, label string) {
	// Font and header scale with the cell so labels stay proportional at any DPI.
	pts := cell * 0.042
	headerH := pts * 1.8
	pad := pts * 0.5
	dc.SetFontFace(face(pts))
	dc.SetRGB(0.97, 0.97, 0.98)
	dc.DrawRectangle(ox+1, oy+1, cell-2, cell-2)
	dc.Fill()
	dc.SetRGB(0.12, 0.12, 0.16)
	dc.DrawString(label, ox+pad, oy+pts*1.1)

	byBin := map[int][]rbox{}
	maxBin := -1
	for _, p := range resp.Placements {
		// rbox is (x,y,z,w,d,h); placement W=width(x), D=depth(y), H=height(z).
		byBin[p.BinIndex] = append(byBin[p.BinIndex], rbox{p.X, p.Y, p.Z, p.W, p.D, p.H, colorOf(p.ItemID)})
		if p.BinIndex > maxBin {
			maxBin = p.BinIndex
		}
	}
	n := maxBin + 1
	if n <= 0 {
		return
	}
	// Show up to maxShow bins across the cell width; note any overflow.
	const maxShow = 6
	show := int(math.Min(float64(n), maxShow))
	bw := cell / float64(show)
	bh := cell - headerH
	for b := 0; b < show; b++ {
		drawBin(dc, ox+float64(b)*bw, oy+headerH, bw, bh, dim, byBin[b])
	}
	if n > show {
		dc.SetRGB(0.4, 0.4, 0.45)
		dc.DrawString(fmt.Sprintf("+%d more bins", n-show), ox+pad, oy+cell-pad)
	}
}

func savePNG(file string, img image.Image) error {
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}

func algoLabel(a string) string {
	switch a {
	case "ff":
		return "First-Fit"
	case "ffd":
		return "FFD"
	case "blf":
		return "BLF"
	case "ems":
		return "EMS"
	case "fit":
		return "Fit"
	case "heightmap":
		return "Heightmap"
	case "laff":
		return "LAFF"
	case "layer":
		return "Layer"
	case "blocks":
		return "Blocks"
	case "assemble":
		return "Assemble"
	case "auto":
		return "Auto"
	default:
		return a
	}
}

// loadScenario reads a webdemo-saved scenario (.json) into a render scenario.
func loadScenario(file string, algos []string) (scenario, error) {
	raw, err := os.ReadFile(file)
	if err != nil {
		return scenario{}, err
	}
	var s struct {
		AllowRotate bool `json:"allow_rotate"`
		Bin         struct {
			Width, Height, Depth float64
		} `json:"bin"`
		Items []struct {
			ID                   string `json:"id"`
			Width, Height, Depth float64
			AllowRotate          *bool `json:"allow_rotate"`
		} `json:"items"`
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return scenario{}, err
	}
	items := make([]packapi.ItemSpec, len(s.Items))
	for i, it := range s.Items {
		rot := s.AllowRotate
		if it.AllowRotate != nil {
			rot = *it.AllowRotate
		}
		items[i] = packapi.ItemSpec{ID: it.ID, Width: it.Width, Height: it.Height, Depth: it.Depth, AllowRotate: rot}
	}
	base := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
	return scenario{
		slug:  base,
		title: fmt.Sprintf("%s — %d items into %g×%g×%g", base, len(items), s.Bin.Width, s.Bin.Height, s.Bin.Depth),
		bin:   packapi.BinSpec{Width: s.Bin.Width, Height: s.Bin.Height, Depth: s.Bin.Depth},
		items: items, algos: algos,
	}, nil
}

// ── deterministic item generators (mirror packapi's benchmark instances) ──────

func mixItems(n int, seed uint32) []packapi.ItemSpec {
	next := lcg(seed)
	sz := []float64{1, 2, 2, 3, 3, 4, 4, 5, 6}
	out := make([]packapi.ItemSpec, n)
	for i := range out {
		pick := func() float64 { return sz[int(next()*float64(len(sz)))%len(sz)] }
		out[i] = packapi.ItemSpec{ID: strconv.Itoa(i), Width: pick(), Depth: pick(), Height: pick(), AllowRotate: true}
	}
	return out
}

func cartonItems(n int, seed uint32) []packapi.ItemSpec {
	next := lcg(seed)
	skus := [][3]float64{
		{6, 6, 6}, {6, 6, 3}, {6, 6, 2}, {6, 3, 3}, {4, 4, 4},
		{3, 3, 6}, {12, 6, 2}, {6, 12, 3}, {4, 4, 2}, {3, 6, 4},
	}
	out := make([]packapi.ItemSpec, n)
	for i := range out {
		k := skus[int(next()*float64(len(skus)))%len(skus)]
		out[i] = packapi.ItemSpec{ID: strconv.Itoa(i), Width: k[0], Depth: k[1], Height: k[2], AllowRotate: true}
	}
	return out
}

// lcg returns a deterministic [0,1) generator matching packapi's benchmark LCG.
func lcg(seed uint32) func() float64 {
	s := seed
	if s == 0 {
		s = 1
	}
	return func() float64 { s = s*1664525 + 1013904223; return float64(s>>8) / (1 << 24) }
}

// ── colour palette ────────────────────────────────────────────────────────────

var palette = []color.RGBA{
	{0xf9, 0x73, 0x16, 255}, {0xe8, 0x79, 0xf9, 255}, {0x2d, 0xd4, 0xbf, 255},
	{0xfa, 0xcc, 0x15, 255}, {0x81, 0x8c, 0xf8, 255}, {0xfb, 0x92, 0x3c, 255},
	{0x4a, 0xde, 0x80, 255}, {0x38, 0xbd, 0xf8, 255}, {0xf4, 0x72, 0xb6, 255},
	{0xa3, 0xe6, 0x35, 255}, {0xc0, 0x84, 0xfc, 255}, {0x60, 0xa5, 0xfa, 255},
}

// buildPalette assigns a stable colour to each item id (input order) so the same
// item is the same colour across every algorithm's render.
func buildPalette(items []packapi.ItemSpec) func(string) color.RGBA {
	m := make(map[string]color.RGBA, len(items))
	for i, it := range items {
		m[it.ID] = palette[i%len(palette)]
	}
	return func(id string) color.RGBA {
		if c, ok := m[id]; ok {
			return c
		}
		return color.RGBA{0xb0, 0xb0, 0xb8, 255}
	}
}
