// Command render produces PNG renders of how each packing algorithm solves a set
// of benchmark instances — a browserless, pure-Go stand-in for the WebGL demo,
// meant for embedding in docs/READMEs.
//
// The scenarios are the SAME instances the packapi benchmarks race (loaded from
// packapi.BenchScenarios, backed by packapi/benchmarks.json) so renders and the
// benchmark table never drift. For every scenario it solves the instance with
// each algorithm (via packapi), renders the resulting bins — isometric for 3-D,
// flat top-down for 2-D, stacked capacity bars for 1-D — and tiles the algorithms
// into one contact-sheet PNG per scenario. A Markdown block linking the images is
// printed to stdout (and written to <out>/README.md) for pasting into docs.
//
// It is a SEPARATE module (its own go.mod, replace → parent) so its image deps
// never reach the main module. Run it from this directory:
//
//	cd cmd/render && go run .                 # writes ../../docs/renders/*.png
//	go run . -out /tmp/r -size 300 -scn 3d    # custom output / cell size / subset
//	go run . -input saved.json                # render a saved webdemo scenario
//
// These are the real (large) benchmark instances, so thumbnails are dense; pick a
// big -size and use -scn/-algos to focus. Solves are timeboxed (-timeout); an
// algorithm that overruns is drawn as a DNF cell, matching the benchmark table.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"math"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/W-Floyd/go-pack-bins/packapi"
	"github.com/fogleman/gg"
	"github.com/golang/freetype/truetype"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/goregular"
)

// labelFont is the parsed scalable Go font used for cell labels; a TrueType face
// (rather than a fixed bitmap font) keeps text crisp and proportional at any DPI.
var labelFont = func() *truetype.Font {
	f, err := truetype.Parse(goregular.TTF)
	if err != nil {
		panic(err)
	}
	return f
}()

func face(points float64) font.Face {
	return truetype.NewFace(labelFont, &truetype.Options{Size: points})
}

// scenario is one instance to render: a slug (for the file name), a human title,
// the solve mode, the bin, an optional contact spec, the items, and the
// algorithms to render.
type scenario struct {
	slug, title, mode string
	bin               packapi.BinSpec
	contact           packapi.ContactSpec
	items             []packapi.ItemSpec
	algos             []string
}

// defaultAlgos is the algorithm set used for a -input scenario (which carries no
// algos of its own); "auto" is omitted as it just renders whichever wins.
var defaultAlgos = []string{"ff", "ffd", "blf", "ems", "fit", "heightmap", "laff", "layer", "blocks", "assemble"}

func main() {
	out := flag.String("out", "../../docs/renders", "output directory for PNGs + README.md")
	mdPrefix := flag.String("mdprefix", "docs/renders", "path prefix used in the emitted Markdown image links")
	cell := flag.Int("size", 560, "cell size in pixels (per algorithm)")
	cols := flag.Int("cols", 3, "algorithms per row in the contact sheet")
	algoFilter := flag.String("algos", "", "comma-separated subset of algorithms to render (default: each scenario's own set)")
	scnFilter := flag.String("scn", "", "render only scenarios whose slug contains this substring")
	timeout := flag.Duration("timeout", 15*time.Second, "per-solve time budget; an algorithm that overruns is drawn as a DNF cell")
	input := flag.String("input", "", "render a saved webdemo scenario (.json) instead of the benchmark set")
	flag.Parse()

	var scenarios []scenario
	if *input != "" {
		sc, err := loadScenario(*input, defaultAlgos)
		if err != nil {
			fmt.Fprintln(os.Stderr, "render: ", err)
			os.Exit(1)
		}
		scenarios = []scenario{sc}
	} else {
		for _, s := range packapi.BenchScenarios() {
			scenarios = append(scenarios, scenario{
				slug: s.Slug, title: s.Title, mode: s.Mode,
				bin: s.Bin, contact: s.Contact, items: s.Items, algos: s.Algos,
			})
		}
	}
	// A -algos filter overrides every scenario's own algorithm set.
	if *algoFilter != "" {
		sub := strings.Split(*algoFilter, ",")
		for i := range scenarios {
			scenarios[i].algos = sub
		}
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "render: ", err)
		os.Exit(1)
	}

	var md strings.Builder
	md.WriteString("# Algorithm packing renders\n\n")
	md.WriteString("Renders of each algorithm's packing on the benchmark instances, generated by `cmd/render` (no browser).\n")

	for _, sc := range scenarios {
		if *scnFilter != "" && !strings.Contains(sc.slug, *scnFilter) {
			continue
		}
		img := renderScenario(sc, *cell, *cols, *timeout)
		file := filepath.Join(*out, sc.slug+".png")
		if err := savePNG(file, img); err != nil {
			fmt.Fprintln(os.Stderr, "render: ", err)
			os.Exit(1)
		}
		link := path.Join(*mdPrefix, sc.slug+".png")
		fmt.Printf("rendered %s (%d algos) -> %s\n", sc.slug, len(sc.algos), file)
		fmt.Fprintf(&md, "\n## %s\n\n![%s](%s)\n", sc.title, sc.title, link)
	}

	mdPath := filepath.Join(*out, "README.md")
	if err := os.WriteFile(mdPath, []byte(md.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "render: ", err)
		os.Exit(1)
	}
	fmt.Println("\nMarkdown written to", mdPath)
	fmt.Print("\n", md.String())
}

// renderScenario solves the instance with each algorithm and tiles the per-algo
// renders into one contact-sheet image.
func renderScenario(sc scenario, cell, cols int, timeout time.Duration) image.Image {
	colorOf := buildPalette(sc.items)
	binCap := binCapacity(sc.mode, sc.bin)

	rows := (len(sc.algos) + cols - 1) / cols
	sheet := gg.NewContext(cols*cell, rows*cell)
	sheet.SetRGB(1, 1, 1)
	sheet.Clear()

	for i, algo := range sc.algos {
		ox := float64((i % cols) * cell)
		oy := float64((i / cols) * cell)

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		resp := packapi.PackCtx(ctx, packapi.PackRequest{
			Mode: sc.mode, Algorithm: algo, Bin: sc.bin, Items: sc.items, Contact: sc.contact,
		})
		dnf := ctx.Err() != nil
		cancel()

		if dnf {
			drawDNF(sheet, ox, oy, float64(cell), algoLabel(algo))
			continue
		}

		fill := 0.0
		if resp.BinsUsed > 0 && binCap > 0 {
			fill = 100 * placedAmount(sc.mode, resp) / (float64(resp.BinsUsed) * binCap)
		}
		label := fmt.Sprintf("%s — %d bins, %.0f%% fill", algoLabel(algo), resp.BinsUsed, fill)
		if n := len(resp.Unplaced); n > 0 {
			label += fmt.Sprintf(", %d unfit", n)
		}
		drawCell(sheet, ox, oy, float64(cell), sc, resp, colorOf, label)
	}
	return sheet.Image()
}

// binCapacity is one bin's total capacity in the mode's unit (length / area /
// volume), used as the fill-percentage denominator.
func binCapacity(mode string, b packapi.BinSpec) float64 {
	switch mode {
	case "1d":
		return b.Width
	case "2d":
		return b.Width * b.Height
	default:
		return b.Width * b.Depth * b.Height
	}
}

// placedAmount sums the placed items' occupancy in the mode's unit.
func placedAmount(mode string, resp packapi.PackResponse) float64 {
	s := 0.0
	for _, p := range resp.Placements {
		switch mode {
		case "1d":
			s += p.W
		case "2d":
			s += p.W * p.H
		default:
			s += p.W * p.D * p.H
		}
	}
	return s
}

// drawCell renders one algorithm's full packing (its bins tiled in a row) into the
// cell at (ox,oy), with a header label. The per-bin drawing follows the mode.
func drawCell(dc *gg.Context, ox, oy, cell float64, sc scenario, resp packapi.PackResponse, colorOf func(string) color.RGBA, label string) {
	// Font and header scale with the cell so labels stay proportional at any DPI.
	pts := cell * 0.042
	headerH := pts * 1.8
	pad := pts * 0.5
	dc.SetFontFace(face(pts))
	dc.SetRGB(0.97, 0.97, 0.98)
	dc.DrawRectangle(ox+1, oy+1, cell-2, cell-2)
	dc.Fill()
	dc.SetRGB(0.12, 0.12, 0.16)
	dc.DrawString(label, ox+pad, oy+pts*1.1)

	byBin := map[int][]packapi.PlacementResult{}
	maxBin := -1
	for _, p := range resp.Placements {
		byBin[p.BinIndex] = append(byBin[p.BinIndex], p)
		if p.BinIndex > maxBin {
			maxBin = p.BinIndex
		}
	}
	n := maxBin + 1
	if n <= 0 {
		return
	}
	// Show up to maxShow bins across the cell width; note any overflow.
	const maxShow = 6
	show := int(math.Min(float64(n), maxShow))
	bw := cell / float64(show)
	bh := cell - headerH
	for b := 0; b < show; b++ {
		x, y := ox+float64(b)*bw, oy+headerH
		switch sc.mode {
		case "1d":
			drawBin1D(dc, x, y, bw, bh, sc.bin.Width, byBin[b], colorOf)
		case "2d":
			drawBin2D(dc, x, y, bw, bh, sc.bin.Width, sc.bin.Height, byBin[b], colorOf)
		default:
			drawBin3D(dc, x, y, bw, bh, [3]float64{sc.bin.Width, sc.bin.Depth, sc.bin.Height}, byBin[b], colorOf)
		}
	}
	if n > show {
		dc.SetRGB(0.4, 0.4, 0.45)
		dc.DrawString(fmt.Sprintf("+%d more bins", n-show), ox+pad, oy+cell-pad)
	}
}

// drawDNF fills a cell with a muted "did not finish" placeholder for an algorithm
// whose solve overran the time budget (as the benchmark table marks DNF).
func drawDNF(dc *gg.Context, ox, oy, cell float64, name string) {
	pts := cell * 0.042
	dc.SetFontFace(face(pts))
	dc.SetRGB(0.95, 0.95, 0.96)
	dc.DrawRectangle(ox+1, oy+1, cell-2, cell-2)
	dc.Fill()
	dc.SetRGB(0.12, 0.12, 0.16)
	dc.DrawString(name+" — DNF (timed out)", ox+pts*0.5, oy+pts*1.1)
	dc.SetRGB(0.7, 0.72, 0.78)
	dc.DrawStringAnchored("DNF", ox+cell/2, oy+cell/2, 0.5, 0.5)
}

func savePNG(file string, img image.Image) error {
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}

func algoLabel(a string) string {
	switch a {
	case "ff":
		return "First-Fit"
	case "bf":
		return "Best-Fit"
	case "wf":
		return "Worst-Fit"
	case "nfd":
		return "NFD"
	case "ffd":
		return "FFD"
	case "bfd":
		return "BFD"
	case "wfd":
		return "WFD"
	case "mffd":
		return "MFFD"
	case "blf":
		return "BLF"
	case "skyline":
		return "Skyline"
	case "ems":
		return "EMS"
	case "fit":
		return "Fit"
	case "heightmap":
		return "Heightmap"
	case "laff":
		return "LAFF"
	case "layer":
		return "Layer"
	case "blocks":
		return "Blocks"
	case "assemble":
		return "Assemble"
	case "rr":
		return "Ruin-Recreate"
	case "arr":
		return "Adaptive R&R"
	case "auto":
		return "Auto"
	default:
		return a
	}
}

// loadScenario reads a webdemo-saved scenario (.json) into a render scenario. Saved
// scenarios are 3-D instances.
func loadScenario(file string, algos []string) (scenario, error) {
	raw, err := os.ReadFile(file)
	if err != nil {
		return scenario{}, err
	}
	var s struct {
		AllowRotate bool `json:"allow_rotate"`
		Bin         struct {
			Width, Height, Depth float64
		} `json:"bin"`
		Items []struct {
			ID                   string `json:"id"`
			Width, Height, Depth float64
			AllowRotate          *bool `json:"allow_rotate"`
		} `json:"items"`
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return scenario{}, err
	}
	items := make([]packapi.ItemSpec, len(s.Items))
	for i, it := range s.Items {
		rot := s.AllowRotate
		if it.AllowRotate != nil {
			rot = *it.AllowRotate
		}
		items[i] = packapi.ItemSpec{ID: it.ID, Width: it.Width, Height: it.Height, Depth: it.Depth, AllowRotate: rot}
	}
	base := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
	return scenario{
		slug:  base,
		title: fmt.Sprintf("%s — %d items into %g×%g×%g", base, len(items), s.Bin.Width, s.Bin.Height, s.Bin.Depth),
		mode:  "3d",
		bin:   packapi.BinSpec{Width: s.Bin.Width, Height: s.Bin.Height, Depth: s.Bin.Depth},
		items: items, algos: algos,
	}, nil
}

// ── colour palette ────────────────────────────────────────────────────────────

var palette = []color.RGBA{
	{0xf9, 0x73, 0x16, 255}, {0xe8, 0x79, 0xf9, 255}, {0x2d, 0xd4, 0xbf, 255},
	{0xfa, 0xcc, 0x15, 255}, {0x81, 0x8c, 0xf8, 255}, {0xfb, 0x92, 0x3c, 255},
	{0x4a, 0xde, 0x80, 255}, {0x38, 0xbd, 0xf8, 255}, {0xf4, 0x72, 0xb6, 255},
	{0xa3, 0xe6, 0x35, 255}, {0xc0, 0x84, 0xfc, 255}, {0x60, 0xa5, 0xfa, 255},
}

// buildPalette assigns a stable colour to each item id (input order) so the same
// item is the same colour across every algorithm's render.
func buildPalette(items []packapi.ItemSpec) func(string) color.RGBA {
	m := make(map[string]color.RGBA, len(items))
	for i, it := range items {
		m[it.ID] = palette[i%len(palette)]
	}
	return func(id string) color.RGBA {
		if c, ok := m[id]; ok {
			return c
		}
		return color.RGBA{0xb0, 0xb0, 0xb8, 255}
	}
}
